In [25]:
# -*- coding: utf-8 -*-
"""Introdução a Collections

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xajf8Uy5Mm_1ZfpSHj5JaHtw9TiSgV0u
"""

idade1 = 39
idade2 = 30
idade3 = 27
idade4 = 18

print(idade1)
print(idade2)
print(idade3)
print(idade4)

idades = [39, 30, 27, 18]

type(idades)

len(idades)

idades[0]

idades

print(idades[1])
print(idades[2])
print(idades[3])

idades.append(15)

idades

idades[4]

#idades[5]

39
30
27
18
30
27
18

15

In [26]:
for idade in idades:
  print(idade)

idades.remove(30)

idades

39
30
27
18
15

[39, 27, 18, 15]

In [27]:
#idades.remove(30)

idades.append(15)

idades

idades.remove(15)

idades

idades.append(27)
idades.remove(27)
idades

28 in idades

15 in idades

if 15 in idades:
  idades.remove(15)

idades

if 28 in idades:
  idades.remove(28)

idades

idades.append(19)
idades

idades.insert(0, 20)
idades

idades = [20, 39, 18]
idades

idades.append([27, 19])

idades

[20, 39, 18, [27, 19]]

In [28]:
for elemento in idades:
  print("Recebi o elemento", elemento)

idades = [20, 39, 18]
idades.extend([27, 19])
idades

Recebi o elemento 20
Recebi o elemento 39
Recebi o elemento 18
Recebi o elemento [27, 19]

[20, 39, 18, 27, 19]

In [29]:
for idade in idades:
  print(idade + 1)

21
40
19
28
20

In [30]:
idades_no_ano_que_vem = []
for idade in idades:
  idades_no_ano_que_vem.append(idade+1)
idades_no_ano_que_vem

[21, 40, 19, 28, 20]

In [31]:
idades_no_ano_que_vem = [idade+1 for idade in idades]
idades_no_ano_que_vem

[21, 40, 19, 28, 20]

In [32]:
[idade for idade in idades if idade > 21]

idades

[20, 39, 18, 27, 19]

In [33]:
def proximo_ano(idade):
  return idade+1

[proximo_ano(idade) for idade in idades if idade > 21]

[40, 28]

In [34]:
def faz_processamento_de_visualizacao(lista):
  print(len(lista))
  lista.append(13)

idades = [16, 21, 29, 56, 43]
faz_processamento_de_visualizacao(idades)
idades

5

[16, 21, 29, 56, 43, 13]

In [35]:
def faz_processamento_de_visualizacao(lista = []):
  print(len(lista))
  print(lista)
  lista.append(13)

faz_processamento_de_visualizacao()

faz_processamento_de_visualizacao()

faz_processamento_de_visualizacao()

faz_processamento_de_visualizacao()

0
[]
1
[13]
2
[13, 13]
3
[13, 13, 13]

In [36]:
def faz_processamento_de_visualizacao(lista = list()):
  print(len(lista))
  print(lista)
  lista.append(13)

faz_processamento_de_visualizacao()
faz_processamento_de_visualizacao()

0
[]
1
[13]

In [37]:
def faz_processamento_de_visualizacao(lista = None):
  if lista == None:
    lista = list()
  print(len(lista))
  print(lista)
  lista.append(13)

faz_processamento_de_visualizacao()
faz_processamento_de_visualizacao()
faz_processamento_de_visualizacao()
faz_processamento_de_visualizacao()

0
[]
0
[]
0
[]
0
[]

**OBJETOS PRÓPRIOS**

In [38]:
class ContaCorrente:
  
  def __init__(self, codigo):
    self.codigo = codigo
    self.saldo = 0

  def deposita(self, valor):
    self.saldo += valor
    
  def __str__(self):
    return "[>>Codigo {} Saldo {}<<]".format(self.codigo, self.saldo)

In [39]:
conta_do_gui = ContaCorrente(15)
print(conta_do_gui)

[>>Codigo 15 Saldo 0<<]

In [40]:
conta_do_gui.deposita(500)
print(conta_do_gui)

[>>Codigo 15 Saldo 500<<]

In [41]:
conta_da_dani = ContaCorrente(47685)
conta_da_dani.deposita(1000)
print(conta_da_dani)

[>>Codigo 47685 Saldo 1000<<]

In [42]:
contas = [conta_do_gui, conta_da_dani]
for conta in contas:
  print(conta)

[>>Codigo 15 Saldo 500<<]
[>>Codigo 47685 Saldo 1000<<]

In [43]:
contas = [conta_do_gui, conta_da_dani, conta_do_gui]
print(contas[0])
conta_do_gui.deposita(100)
print(contas[0])

[>>Codigo 15 Saldo 500<<]
[>>Codigo 15 Saldo 600<<]

In [44]:
print(conta_do_gui)
print(contas[2])
contas[2].deposita(300)
print(conta_do_gui)

[>>Codigo 15 Saldo 600<<]
[>>Codigo 15 Saldo 600<<]
[>>Codigo 15 Saldo 900<<]

In [45]:
def deposita_para_todas(contas):
  for conta in contas:
    conta.deposita(100)

In [46]:
contas = [conta_do_gui, conta_da_dani]
print(contas[0], contas[1])
deposita_para_todas(contas)
print(contas[0], contas[1])

[>>Codigo 15 Saldo 900<<] [>>Codigo 47685 Saldo 1000<<]
[>>Codigo 15 Saldo 1000<<] [>>Codigo 47685 Saldo 1100<<]

In [47]:
contas.insert(0,76)
print(contas[0], contas[1], contas[2])

76 [>>Codigo 15 Saldo 1000<<] [>>Codigo 47685 Saldo 1100<<]

In [48]:
deposita_para_todas(contas)
print(contas[0], contas[1], contas[2])

AttributeError: ignored

In [ ]:
guilherme = ('Guilherme', 37, 1981) # tupla
daniela = ('Daniela', 31, 1987)
# paulo = (39, 'Paulo', 1979) # ruim

In [ ]:
guilherme.append(6754)

In [ ]:
conta_do_gui = (15, 1000)
# conta_do_gui.deposita() # variação OO
conta_do_gui[1]

In [ ]:
conta_do_gui[1] += 100

In [ ]:
def deposita(conta): # variação "funcional"(separando o comportamento dos dados)
  novo_saldo = conta[1] + 100
  codigo = conta[0]
  return (codigo, novo_saldo)

In [ ]:
deposita(conta_do_gui)
conta_do_gui

In [ ]:
conta_do_gui = deposita(conta_do_gui)
conta_do_gui

In [ ]:
usuarios = [guilherme, daniela]
usuarios

In [ ]:
usuarios.append(('Paulo', 39, 1979))
usuarios

In [ ]:
usuarios[0][0] = 'Guilherme Silveira'

In [ ]:
conta_do_gui = ContaCorrente(15)
conta_do_gui.deposita(500)
conta_da_dani = ContaCorrente(234876)
conta_da_dani.deposita(1000)

In [ ]:
contas = (conta_do_gui, conta_da_dani)

In [ ]:
for conta in contas:
  print(conta)

In [ ]:
contas.append(423768)

In [ ]:
contas[0].deposita(300)

In [ ]:
for conta in contas:
  print(conta)

**HERANÇA E POLIMORFISMO**

In [ ]:
from abc import ABCMeta, abstractmethod

class Conta(metaclass=ABCMeta):
  
  def __init__(self, codigo):
    self._codigo = codigo
    self._saldo = 0

  def deposita(self, valor):
    self._saldo += valor

  @abstractmethod
  def passa_o_mes(self):
    pass

  def __str__(self):
    return "[>>Codigo {} Saldo {}<<]".format(self._codigo, self._saldo)

In [ ]:
print(Conta(88))

In [ ]:
class ContaCorrente(Conta):
  
  def passa_o_mes(self):
    self._saldo -= 2
    
class ContaPoupanca(Conta):
  
  def passa_o_mes(self):
    self._saldo *= 1.01
    self._saldo -= 3

class ContaInvestimento(Conta):
  pass

In [ ]:
ContaInvestimento(764)

In [ ]:
conta16 = ContaCorrente(16)
conta16.deposita(1000)
conta16.passa_o_mes()
print(conta16)

In [ ]:
conta17 = ContaPoupanca(17)
conta17.deposita(1000)
conta17.passa_o_mes()
print(conta17)

In [ ]:
conta16 = ContaCorrente(16)
conta16.deposita(1000)
conta17 = ContaPoupanca(17)
conta17.deposita(1000)
contas = [conta16, conta17]

In [ ]:
for conta in contas:
  conta.passa_o_mes() # duck typing
  print(conta)

**Evitaremos usar array puro. se precisamos de trabalho numérico, é costume usar o numpy**

In [ ]:
import array as arr

arr.array('d', [1, 3.5])

arr.array('d', [1, 3.5, 'Guilherme'])

In [ ]:
!pip install numpy

In [49]:
import numpy as np

numeros = np.array([1, 3.5])
numeros

numeros + 3

array([4. , 6.5])

In [54]:
class ContaSalario:

  def __init__(self, codigo):
    self._codigo = codigo
    self._saldo = 0

  def deposita(self, valor):
    self._saldo += valor

  def __str__(self):
    return "[>>Codigo {} Saldo {}<<]".format(self._codigo, self._saldo)

In [55]:
conta1 = ContaSalario(37)
print(conta1)

[>>Codigo 37 Saldo 0<<]

In [56]:
conta2 = ContaSalario(37)
print(conta2)

[>>Codigo 37 Saldo 0<<]

In [57]:
conta1 == conta2

False

In [61]:
contas = [conta1]
conta1 in contas

True

In [62]:
conta2 in contas

False

In [63]:
class ContaSalario:

  def __init__(self, codigo):
    self._codigo = codigo
    self._saldo = 0

  def __eq__(self, outro):
    return self._codigo == outro._codigo

  def deposita(self, valor):
    self._saldo += valor

  def __str__(self):
    return "[>>Codigo {} Saldo {}<<]".format(self._codigo, self._saldo)

In [64]:
conta1 = ContaSalario(37)
conta2 = ContaSalario(37)
conta1 == conta2

True

In [65]:
conta1 in [conta2]

True

In [66]:
conta2 in [conta1]

True

In [71]:
class ContaSalario:

  def __init__(self, codigo):
    self._codigo = codigo
    self._saldo = 0

  def __eq__(self, outro):
    if type(outro) != ContaSalario:
      return False
      
    return self._codigo == outro._codigo and self._saldo == outro._saldo

  def deposita(self, valor):
    self._saldo += valor

  def __str__(self):
    return "[>>Codigo {} Saldo {}<<]".format(self._codigo, self._saldo)

In [75]:
conta1 = ContaSalario(37)
conta2 = ContaCorrente(37)
conta3 = ContaSalario(37)
conta1 == conta2

False

In [76]:
conta1 == conta3

True

In [69]:
conta1.deposita(10)

In [70]:
conta1 == conta2

False

In [77]:
class ContaSalario:

  def __init__(self, codigo):
    self._codigo = codigo
    self._saldo = 0

  def __eq__(self, outro):
    if type(outro) != ContaSalario:
      return False
      
    return self._codigo == outro._codigo and self._saldo == outro._saldo

  def deposita(self, valor):
    self._saldo += valor

  def __str__(self):
    return "[>>Codigo {} Saldo {}<<]".format(self._codigo, self._saldo)

class ContaMultiploSalario(ContaSalario):
  pass

In [81]:
isinstance(ContaCorrente(37), ContaCorrente)

True